Attempt to use MethodHandles.lookup().defineClass().
Try to use MethodHandles.lookup().defineClass() instead of ClassLoader.defineClass(), as suggested on https://github.com/EsotericSoftware/reflectasm/issues/64
This will get rid of the following warnings:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.esotericsoftware.reflectasm.AccessClassLoader (file:/.m2/repository/com/esotericsoftware/reflectasm/1.11.7/reflectasm-1.11.7.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.reflectasm.AccessClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Although as it is, these changes break some of the unit tests, with failures like the following:

```
java.lang.LinkageError: loader 'app' attempted duplicate class definition for com.esotericsoftware.reflectasm.ClassLoaderTest$Test. (com.esotericsoftware.reflectasm.ClassLoaderTest$Test is in unnamed module of loader 'app')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.System$2.defineClass(System.java:2126)
	at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:962)
	at com.esotericsoftware.reflectasm.ClassLoaderTest$TestClassLoader1.loadClass(ClassLoaderTest.java:162)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.esotericsoftware.reflectasm.ClassLoaderTest.testRemoveClassloaders(ClassLoaderTest.java:99)
```